PROPERTIES_FILTER = {
    "Synthesis Yield": ["Synthesis yield", "yield"],
    "Space Group": ["Space Group", "crystallographic space group"],
    "Crystal System": ["Crystal System"],
    "Cell Volume": ["Cell Volume", "unit cell volume", "Crystal System Volume"],
    "Density": ["Density", "Calculated Density", "density calculated", "dc", "dcalc", "d calc", "d calcd", "dcalcd", "ρcalc", "ρc", "ρ", "ρ calcd"],
    "Thermal Stability": ["Thermal Stability", "Stability temperature", "decomposition temperature"],
    "Chemical Formula": ["Chemical Formula", "Formula", "Molecular Formula"],
    "Formula Weight": ["Formula Weight", "Molecular Weight", "Formula Mass", "Molar Mass"],
    "Light Absorption Coefficient": ["Light Absorption Coefficient", "Absorption Coefficient"],
    "Topology": ["Topology", "framework topology", "network topology", "structural topology"],
    "Langmuir Surface Area": ["Langmuir surface area", "surface area langmuir",],
    "BET Surface Area": ["Surface Area",  "surface area bet", "bet surface area"],
    "Surface Area": ["Surface Area"],
    "Magnetic Susceptibility": ["Magnetic Susceptibility", "Magnetic Susceptibility at room temperature", "Magnetic Susceptibility at 300 K", "weiss constant", "curie constant"],
    "Magnetic Moment": ["Magnetic Moment", "effective magnetic moment"],
    "Pore Volume": ["Pore Volume", "void volume", "void space", "free volume", "effective free volume", "porosity", "Solvent-accessible Volume", "Solvent Accessible Volume"],
    "Pore Diameter": ["Pore Diameter", "Pore size"],
    "Hydrocarbon Adsorption": ['C3H8 uptake capacity', 'C2H2 Storage Capacity', 'MeOH Adsorption', 'C3H8 adsorption capacity', 'C2H4 Uptake Capacity', 'Ethene Uptake', '1-Propanol Adsorption Capacity', 'Propyne Adsorption Capacity', "Methanol uptake", 'Ethene Uptake', 'C3H8 adsorption capacity', "C2H4 Uptake Capacity", 'CH3CH2OH Sorption Capacity', "c2h6 uptake", "c2h6 storage", "c2h6 adsorption", "ethane storage", "ethane adsorption", "ethane storage capacity", "ethane adsorption capacity", "c2h6 adsorption capacity","c2h4 uptake", "c2h4 storage", "c2h4 adsorption", "ethene storage", "ethene adsorption", "ethene storage capacity", "ethene adsorption capacity", "c2h4 adsorption capacity", "c2h2 uptake", "c2h2 storage", "c2h2 adsorption", "acetylene adsorption", "acetylene storage capacity", "ethyne adsorption", "ethyne storage capacity", "acetylene adsorption capacity", "c2h2 adsorption capacity", "hexene adsorption", "hexene storage capacity", "hexene uptake", "hexane adsorption", "hexane storage capacity", "hexane uptake", "cyclohexane storage", "cyclohexane adsorption", "hexane adsorption capacity", "hexene adsorption capacity", "ch3oh uptake", "benzene adsorption capacity"],
    "CO2 Uptake": ['CO2 Adsorption', "co2 Uptake", "CO2 adsorption capacity", "carbon dioxide uptake", "CO2 Storage capacity", "carbon dioxide storage", "carbon dioxide adsorption", "co2 adsorption capacity", "carbon dioxide adsorption capacity"],
    "H2 Uptake": ['H2 Uptake Capacity', 'H2 Adsorption Capacity', 'H2 Sorption Capacity', "h2 storage capacity", "h2 uptake", "h2 storage", "h2 adsorption", "hydrogen uptake", "hydrogen storage capacity", "hydrogen adsorption", "hydrogen adsorption", "hydrogen adsorption capacity", "h2 adsorption capacity"],
    "N2 Uptake": ["n2 uptake", "n2 storage", "n2 adsorption", "nitrogen uptake", "nitrogen storage capacity", "nitrogen adsorption", "nitrogen adsorption", "nitrogen adsorption capacity", "n2 adsorption capacity"],
    "Color": ["color", "crystal color"],
    "Band Gap": ["band gap"],
    "Excitation Wavelength": ["excitation wavelength", "photoluminescent excitation wavelength", "emission excitation wavelength", "Luminescence Excitation Maximum"],
    "Emission Wavelength": ["emission wavelength", "fluorescence emission wavelength", "fluorescence emission peak", "fluorescence emission maximum", "fluorescence maximum", "fluorescence peak", "photoluminescence emission wavelength", "photoluminescence emission maximum", "emission maximum", "photoluminescence emission peak", "photoluminescence maximum", "photoluminescence peak", "luminescence emission wavelength", "luminescence emission maximum", "emission peak", "luminescence emission peak", "luminescence maximum", "luminescence peak",],
    "Coordination Geometry": ["Coordination Geometry", "Coordination Environment", "coordination geometry of", "coordination geometry -"],
    "Coordination Number": ["Coordination number"],
    "Methane Uptake": ['Methane Storage', 'CH4 uptake capacity', "CH4 Adsorption", "CH4 uptake", "ch4 adsorption", "ch4 storage", "ch4 storage capacity", "ch4 adsorption capacity", "methane adsorption capacity", 'Methane Uptake', "Methane Storage Capacity"],
    "Iodine Adsorption": ['Iodine Adsorption', 'Iodine Adsorption Capacity', 'I2 Sorption Capacity', 'I2 Adsorption']
}
PROPERTIES_FILTER["Remove"] = [
    'Iodine Desorption Rate', 'Iodine Adsorption Rate', 'IR Absorption',
    'CO2 Adsorption Step', 'Dye Adsorption Capacity', 'N2 and H2 Adsorption',
    'H2S Uptake', 'Enthalpy of Carbon Dioxide Adsorption', 'N₂ Uptake Capacity',
    "bond angles", "water adsorption capacity", 'D2 Uptake', 'H2O Uptake',
    "angles", "heat of adsorption", "adsorption energy",'Uptake', 'Uptake Capacity',
    "unit cell angles", "cd4 uptake", "storage capacity",'H2 adsorption curve',
    "bond distances", "adsorption heat", "saturation capacity", "hydrogen adsorption enthalpy",
    "hydrogen bond geometry", "carbon dioxide adsorption enthalpy", "O2 adsorption capacity",
    "unique reflections", "adsorption enthalpy", "adsorption sites", 'Hydrogen Storage Density',
    "unit cell parameter", "unit cell dimension", "cell parameters", 'Gas Adsorption',
    "lattice parameters", "CO2 working capacity", "CO2 adsorption order"
    "ir spectrum", "ir spectroscopy", "ir data", "ir spectra peaks", "ir peaks", "ir absorption bands", "ft ir peaks",
    "elemental analysis (carbon)", "(hydrogen)", "(nitrogen)",
    "hydrogen bonds", "O2 Uptake", "SO2 Adsorption capacity", 'Methanol Uptake Capacity'
    "carbon content", "hydrogen content", 'Metal Ion Adsorption Capacity', 
    "wavelength", "emission wavelength range", "Sorption Capacity",
    "photoluminescence", "photoluminescence emission maxima", 'Excess CH4 Uptake Capacity',
    "Luminescence", 'NO Adsorption Capacity', 'Hg2+ Adsorption Capacity',
    "emission peaks", 'N2O Adsorption Capacity', 'n-BuOH Adsorption',
    "Coordination Mode", 'Methanol Adsorption Capacity', "Methanol Uptake",
    "Coordination Sphere", "so2 uptake", "heat of hydrogen adsorption", 'NH3 Uptake Capacity',
    "Elemental analysis", "chemical formula weight", 'H2O Adsorption', 'MeOH Uptake', 'Oxygen Adsorption',
    "Elemental analysis - carbon", 'i2 desorption temperature', 'tliesst temperature',
    "Elemental analysis - hydrogen", 'reaction temperature', 'thermal stability ranking',
    "Elemental analysis - nitrogen", 'water stability', 'chemical stability', 'CO₂ Uptake Capacity',
    "ch3oh adsorption", "coordination geometry angles", 'molecular weight control',
    "emission spectra", "emission maxima", "emission peaks", 'photoluminescence emission peaks', 'fluorescence emission maxima',
    "photoluminescence emission intensity", "emission intensity", "photoluminescence emission wavelengths", "luminescent emission band maxima",
    "photoluminescent emission wavelengths", 'luminescence emission maxima', 'luminescence emission peaks', 'emission maximum wavelengths',
    'fluorescence emission bands', 'luminescence wavelengths', 'photoluminescence emission intensity', 'photoluminescence emission range',
    'photoluminescence excitation peaks', 'magnetic susceptibility decrease', 'magnetic susceptibility maximum temperature',
    'magnetic susceptibility increase', 'ac susceptibility', 'magnetic susceptibility model', 'solvent-accessible void change',
    'solvent-accessible ratio', "molecular unit", "emission color", "Emission Type", "luminescence appearance", "Photoluminescence Mechanism",
    "Photoluminescence Decay Time", "Fluorescence Spectra", "Photoluminescence (PL) spectra", 'Photoluminescence Peak Shift',
    'Photoluminescence Properties', 'Luminescence Emission Type', 'Photoluminescence Response', "Fluorescent emission state",
    'Photoluminescence Mechanism', 'Fluorescence Emission Type', 'Luminescence Pattern', 'Photoluminescence Response',
    'Magnetic Susceptibility - Phase Transition Temperature', 'Magnetic Susceptibility Fitting', "adsorption capacity",
]

APPLICATIONS_FILTER = {
    "Carbon Storage": [
        "CO2 Retention","Carbon Storage","Storage of Carbon Dioxide",
        "Carbon Dioxide Retention", "CO2 Storage Materials",
        "Retention of Carbon Dioxide", "CO2 Management",
        'CO2 and H2 storage', 'H2 and CO2 storage',
    ],
    "Carbon Capture": [
        "CO2 Adsorption", "Carbon Capture", "CO2 Sequestration",
        "Carbon Dioxide Capture", "Carbon Dioxide Storage",
        "Carbon Dioxide Adsorption", "CO2 Uptake", "CO2",
        "CO2 Capture",  "Carbon Sequestration", 'Carbon dioxide and methane sorption',
        "Capture of CO2", "Carbon Adsorption",
        "Carbon Dioxide Uptake", 'CO2 adsorption/separation',
        "Removing CO2", 'CO2 adsorption and separation',
        "Sequestration of Carbon", 'CO2/CH4 and CO2/N2 separation',
        "Carbon Absorption", "Capture of Carbon Dioxide", 
        "carbon capture", "co2 gas adsorption", "co2 gas", "carbon dioxide gas",
        "co2 storage", "co2 storage and separation", "direct air capture", "CO2/N2 Separation",
        "direct air capture of co2", 'CO2 gas selectivity', 
    ],
    "Methane Capture": [
        "Methane capture", "CH4 capture", "capture of ch4",
        "capture of methane", 'CH4/N2 separation', 
    ],
    "Methane Storage": [
        "Methane Adsorption", "CH4 Adsorption", "Methane Sequestration",
        "Methane Retention", 'H2 and CH4 storage', 'Carbon dioxide and methane sorption',
        "Capture of Methane", "CH4 Uptake", 'CO2/CH4 and CO2/N2 separation',
        "Methane Management", "Methane Adsorption Materials",
        "Methane Sequestration Systems", 'CH4 storage',
        "CH4 capture", "methane sorption", "ch4 sorption",
        "CO2/CH4 Separation", "methane storage", "methane CH4 storage",
    ],
    "Hydrogen Capture": [
        "Capture of Hydrogen", "h2 capture", "hydrogen capture", 'H2 purification'
        'Hydrogen storage and purification', 'H2 purification'
    ],
    "Hydrogen Storage": [
        "H2 Adsorption", "Hydrogen Uptake", "H2 Sequestration",
        "Hydrogen Capture", 'H2 and CH4 storage', 'H2 and CO2 storage',
        "Hydrogen Absorption", 'Hydrogen storage and purification',
        "H2 Adsorption Materials", "H2 Management", 
        "h2 sorption", "hydrogen sorption",
        "h2 uptake", "h2 gas adsorption", 
        "H2/CO2 Separation", 'CO2 and H2 storage',
        "Hydrogen Storage", "H2 Storage", "Storage of Hydrogen",
        "h2 storage applications", "H2 Retention", "Hydrogen Retention",
        "Hydrogen Retention Systems",'CH4 storage',
    ],
    "Hydrocarbon Separation": [
        "Hydrocarbon Separation", "hexene adsorption", 'Acetylene storage and separation',
        "c2h2 uptake", "c2h2 removal", "hexene uptake", "hexane uptake",
        "hexane adsorption", "c2h4 removal", "c2h6 adsorption",
        "c2h2 capture", "c2h6 capture", "c2h2 adsorption", 'Acetylene storage and purification',
        "c2h2 storage", 'C2/C1 separation', 'C2H2/CO2 separation',
        'C2H2/CH4 and C2H2/CO2 separation', 'C2H2 storage and C2H2/CO2 separation',
    ],
    "Gas Adsorbent Material": [
        "Gas Selectivity", "Gas Diffusion", "Mixed Gas Separation",
        "Gas Mixture Separation", "oxygen adsorption", 'N2/O2 separation',
        "Separation of Gases", "Gas Mixture Selectivity",
        "Gas Adsorption Separation", "Gas Partitioning", 'Gas storage and purification',
        "Gas Cleaning", "Gas Purification", "Gas Isolation",
        "Separation Technology", "Selective Gas Permeability",
        "Gas Filtering", "Gas Mixture Filtration", "gas adsorption",
        "gas storage and separation", "gas sorption applications",
        "n2 adsorption", "n2 uptake", 'Gas storage materials',
        'acetylene storage and separation', 'c2h2 storage and c2h2/co2 separation',
        'N2/Ar separation', 'Air separation', 'Gas storage and purifications',
    ],
    "Heterogeneous Catalysis": [
        "Heterogeneous Catalysis",
    ],
    "Photocatalysis": [
        "Photocatalysis", "photocatalysis degradation of",
        "photocatalytic degradation of", "photocatalytic production",
        "co2 photoreduction", "photoreduction of",

    ],
    "Electrocatalysis": [
        "Electrocatalysis",
        "electrocatalysis", "eletrocatalytic reduction",
        "Reduction Catalysis", "reduction reaction catalysis",
        "catalysis of reduction", "Oxidation Catalysis",
        "CO2 Reduction", "CH4 Reduction", "hydrogen evolution reaction",
        "oxygen reduction", "h2 evolution reaction", "o2 evolution reaction",
        "CO2 fixation", 'Water oxidation',
    ],
    "Catalysis": [
        "Catalysis",
        "Catalytic Activity", "Catalyst", "Enzyme Mimic",
        "Organic Synthesis Catalysis",
        "Catalytic Reaction", "Catalyst Activity", "Catalytic Process",
        "Catalyst Efficiency", "Catalysis Materials", "Reaction Catalysis",
        "Chemical Reaction Catalysis", "asymmetric catalysis",
    ],
    "Water Purification": [
        "Water Purfication",
        "Water Treatment", "Wastewater Filtration",
        "Water Remediation", "Water Decontamination", "Clean Water Production",
        "Fluoride Removal", 'Dye separation',
        "Purification of Water", "Clean Water Treatment",
        "Water Filtration", "Water Cleaning", "Water Detoxification",
        "Safe Drinking Water", "Water Purity", "Water Purification Systems",
        "Filtration of Water", "Water adsorption", "dye adsorption",
    ],
    "Pollutant Removal": [
        "Pollutant Degradation",
        "Pollution Removal", "Degradation of Organic Pollutants",
        "Environmental Remediation", "Toxic Compound Degradation",
        "Organic Pollutant Breakdown", "Industrial Waste Degradation",
        "Pollutant Breakdown", "Pollution Degradation",
        "Organic Degradation", "Pollution Detoxification",
        "Pollutant Remediation", "Decomposition of Pollutants",
        "Toxic Waste Treatment", "Pollutant Neutralization",
        "photocatalytic degradation of organic", "degredation of"
    ],
    "Drug Delivery": [
        "Drug delivery",
        "Targeted Drug Delivery", "Controlled Drug Release",
        "Therapeutic Delivery", "Pharmaceutical Carrier",
        "Bioactive Compound Delivery", "Anticancer Drug Delivery",
        "Drug Release System", "Medication Delivery",
        "Therapeutic Compound Delivery", "Targeted Medication Delivery",
        "Drug Carrier Systems", "Pharmaceutical Delivery Systems"
    ],
    "Photoluminescence": [
        "Photoluminescence",
        "Fluorescence", "Light Emission", "Photonic Properties",
        "Luminescence", "Light Absorption and Emission",
        "Emission of Light", "Light Absorption", "Luminescent materials",
        "Photon Emission", "Light Scattering", "Photoemission",
        "Photonic Activity", "Photoluminescent Materials", "photoluminscence",
        "luminescent properties", "blue-luminescent materials",
        "blue-fluorescent materials",
    ],
    "Energy Storage": [
        "Energy Storage",
        "Battery Materials", "Thermal Energy Storage",
        "Electrochemical Energy Storage", "Energy Retention",
        "Energy Harvesting", "Fuel Cell Materials",
        "Energy Accumulation", "Energy Conservation",
        "Energy Retention Systems", "Energy Storage Materials",
        "Energy Management", "Energy Storage Technology",
        "fuel cells",
    ],
    "Gas Sensing": [
        "Gas sensing",
        "Gas Detection", "Gas Sensor Applications", "Toxic Gas Monitoring",
        "Volatile Organic Compound (VOC) Detection", "Environmental Sensing",
        "Industrial Gas Monitoring", "CO2 Sensor", "NOx Sensor", "SOx Sensor",
        "Detection of Gases", "Gas Monitoring", "Gas Sensing Applications",
        "VOC Sensing", "Toxic Gas Detection", "Gas Analysis"
    ],
    "Membrane Technology": [
        "Membrane technology", "Membrane separation",
        "Gas Separation Membranes", "MOF-Based Membranes",
        "Water Desalination Membranes", "Permeation Membranes",
        "Selective Permeability Membranes", "Membrane Materials",
        "Gas Permeability Membranes", "Filtration Membranes",
        "Membrane Filtration", "Separation Membranes"
    ],
    "Cancer Therapy": [
        "Cancer therapy",
        "Oncological Applications", "Cancer Treatment",
        "Antitumor Activity", "Photodynamic Therapy", "Chemodynamic Therapy",
        "Therapy for Cancer", "Anticancer Therapy",
        "Tumor Treatment", "Cancer Therapeutics",
        "Treatment of Tumors", "Cancer Management"
    ],
    "Sensors": [
        "Chemical Sensors", "Biosensors", "Optical Sensors",
        "Electrochemical Sensors", "MOF-Based Sensing Applications",
        "Detection Sensors", "Sensor Technology", "Analytical Sensors",
        "Sensing Materials", "Sensor Applications", "sensing devices",
        "fluorscent sensing", "sensors", "pressure sensors",
        "luminscent sensors", "detection of nitroaromatic explosives",
        "detection of nitrobenzene", "nitrobenzene detection",
        "detection of acetone", "detection of fe3+ ions", "sensing of fe3+ ions",
        "luminescence sensing", "sensing of small molecules",
        "luminescent probes", "cation sensing", "magnetic sensors devices",
        "sensing applications",
    ],
    "Heavy Metal Removal": [
        "Lead Removal", "Mercury Removal", "Cadmium Removal",
        "Arsenic Removal", "Metal Ion Adsorption", "Heavy Metal Detoxification",
        "Removal of Heavy Metals", "Heavy Metal Filtration",
        "Metal Ion Removal", "Detoxification of Metals",
        "Metal Contamination Removal", "Heavy Metal Removal",
        "Arsenic Removal", "Lead Removal", 
    ],
    "Solar Energy Harvesting": [
        "Solar Cells", "Photovoltaics", "Light Absorption",
        "Solar Energy Conversion", "Solar Panel Materials",
        "Harvesting Solar Energy", "Solar Light Conversion",
        "Solar Energy Materials", "Solar Light Absorption",
        "Solar Energy Systems",
    ],
    "Self-Healing Materials": [
        "Self-Repairing Materials", "Autonomous Healing Materials",
        "Structural Repair Materials", "Self-Reinforcing MOFs",
        "Self-Healing Systems", "Self-Healing Polymers",
        "Materials with Self-Repair Capability", "Self-Fixing Materials"
    ],
    "Data Storage": [
        "Data Retention", "Information Storage", "Memory Storage",
        "Data Preservation", "Digital Storage", "Data Storage Capacity",
        "Data Archiving", "High-Density Storage", "Data Storage Systems",
        "Retention of Information", "Digital Data Preservation",
        "Data Storage Materials", "Data Accumulation"
    ],
    "Optical Devices": [
        "optical materials", "nonlinear optical materials (nlo)", 
        "optical devices", "nonlinear optical properties (nlo)",
        "nonlinear optics (nlo)", "optoelectronic devices",
        "nonlinear optical (nlo) applications", "optics",
        "optoelectronic properties", "optical applications"
    ],
    "Magnetic Refrigeration": [
        "magnetic refrigeration", "cryogenic magnetic refrigeration",
        "cryogenic magnetorefrigeration",
    ],
    "Magnetic Material": [
        "magnetism", "magnetic material", "magnetic properties",
    ],
    "Electrical Conductivity": [
        "eletrical conductivity", "supercapacitors", "semicapacitors",
        "capacitors", "ferroelectricity", "ferroelectric materials",
        "supercapcitor",
    ],
    "Small Molecule Capture": [
        "separation of isomers", "molecular separations",
        "small molecular separations", "small molecular storage",
        "small molecule storage and separation",
        "molecular storage and separation",
    ],
    "Molecular Magnets": [
        "molecular magnets", "molecular magnetism"
    ],
    "Light Emitting Diodes": [
        "light emitting diodes (leds)", "blue-light emitting diodes",
        "blue-light emitting material", "white-light emitting material",
        "blue-light emitting diodes", "white-light emitting diodes",
        "light emitting properties", "white-light emission",
        "solid state lighting",
    ],
    "Iodine Capture": [
        "i2 adsorption", "i2 capture", "i2 separation",
        "iodine adsorption", "iodine capture", "iodine separation",
    ]
}

APPLICATIONS_FILTER["Remove"] = [
    "multiferroics", 'O2/N2 separation',
    "ion exchange", 'CO2 Selectivity', 'Anion separation',
    "adsorption", "storage", "sorption material", 'Separations', 'Separation',
    "adsorptive material", "electrochemical fields",
    "luminescence tuning", 'chiral sorption', 'ethanol adsorption',
    'n-butane adsorption', "biomedical applications",
    "photochemical applications",'protein adsorption', 'solvent storage and separation',
    'Adsorption and separation', 'Solvent adsorption and separation',
    'Molecular adsorption/separation', 'Adsorption and separation',
]