name: Publish to PyPI

# ───────────────────────────────────────────────────────────────
# Trigger: only when a version tag like  v1.2.3  is pushed
# ───────────────────────────────────────────────────────────────
on:
  push:
    tags:
      - "v*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      #  Get the code
      - name: Check out repository
        uses: actions/checkout@v4

      #  Install the requested Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      #  Upgrade build tools and install project deps (optional tests could run here)
      - name: Install build backend
        run: |
          python -m pip install --upgrade pip build

      #  Build wheel and sdist into ./dist
      - name: Build distribution
        run: python -m build --sdist --wheel --outdir dist

      #  Upload to the real PyPI   ───────────────
      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1.12.4
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
